config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'chat/show'

  root 'events#index'  
 
  resources :users
  resources :areas
  resources :prefs
  resources :events
  resources :event_apps do
    resources :stores
  end

  delete '/logout',to:'sessions#destroy'

  get '/event_msgs',to:'event_msgs#index'
  post '/event_msgs',to:'event_msgs#create'


  get '/event_msg_reps/new',to:'event_msg_reps#new'
  post '/event_msg_reps',to:'event_msg_reps#create'

  get '/msgs/index',to:'msgs#index'
  get '/msgs/select_user',to:'msgs#select_user'
  post '/msgs/select_user',to:'msgs#query_user'

  get '/msgs/:id',to:'msgs#new'
  post 'msgs/:id',to:'msgs#create'

  get '/home',to:'home#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
 
  get '*not_found',to:'application#routing_error'
  post '*not_found',to:'application#routing_error'

  mount ActionCable.server => '/cable'
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :event_app, foreign_key: 'event_app_id'
  belongs_to :user, foreign_key: 'store_owner_id'

  validates :name, presence: true
  validates :store_desc, length: { maximum: 2000 }
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :authenticate_user!, only: %i[index create new]
  before_action :store_creator, only: %i[index create new edit]

  def index
    @store = Store.find_by(event_app_id: params[:event_app_id])
  end

  def edit
    @store = Store.find_by(event_app_id: params[:event_app_id])
    render 'stores/index'
  end

  def new
    @event_app_id = params[:event_app_id]
    @store = Store.new
    render 'stores/new'
  end

  def create
    event_app = EventApp.find_by(id: params[:store][:event_app_id])
    @store = Store.new
    @store.event_app_id = event_app.id
    @store.event_id = event_app.event_id
    @store.store_owner_id = current_user.id
    @store.name = params[:store][:name]
    @store.store_desc = params[:store][:store_desc]
    @event_app_id = event_app.event_id

    if @store.save
      flash[:success] = '保存しました'
      redirect_to edit_event_app_store_path(@store.event_app_id, @store.id)
    else
      flash[:error] = '不正な入力があります'
      render 'stores/new'
    end
  end

  def update
    @store = Store.find_by(id: params[:store][:store_id])
    if @store.update(store_params)
      flash.now[:success] = '保存しました'
    else
      flash.now[:error] = '不正な入力があります'
    end
    render 'stores/index'
  end

  def show
    @store = Store.find_by(id: params[:id])
  end

  def destroy
    @store = Store.find_by(id: params[:id])
    event_app_id = @store.event_app_id

    @store.destroy
    flash[:success] = 'イベントを削除しました'
    redirect_to event_app_path(event_app_id)
  end

  private

  def store_params
    params.require(:store).permit(
      :name,
      :store_desc
    )
  end

  def store_creator
    event_app = EventApp.find_by(id: params[:event_app_id])
    redirect_to event_apps_path unless event_app&.user_id == current_user.id
  end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/index.html.slim
section.content
  p.back-to
    | <a href="#{event_app_path(params[:event_app_id])}">
        <i class="fas fa-arrow-left"></i>
      </a>
  .content-item
    h2.page-title 出店情報
    - if @store.nil?
      p.store-new = link_to '新規作成', new_event_app_store_path(params[:event_app_id]), class: 'btn'
    - else
      = form_with method: :patch, model: @store, local: true, url: event_app_store_path(@store.event_id, @store.id) do |f|
        = f.hidden_field :store_id, value: @store.id
        .form_group
          = f.label :name
          br
          = f.text_field :name
          - if @store.errors[:name].any?
            span.form-error = @store.errors.full_messages_for(:name)[0]
        .form_group
          = f.label :store_desc
          br
          = f.text_area :store_desc, class: 'desc'
        = f.submit '登録'
        p.event-new = link_to '削除する', event_app_store_path(@store.event_app_id, @store.id), class: 'btn-min', method: :delete, data: { confirm: '本当に削除してよろしいでしょうか？' }

app/views/stores/new.html.slim
.content
  p.back-to
    | <a href="#{event_app_path(params[:event_app_id])}"><i class="fas fa-arrow-left"></i></a>
  .content-item
    h2.page-title 出店情報の新規作成
    = form_with model: @store, local: true, url: event_app_stores_path(@event_app_id) do |f|
      .form_group
        = f.label :name
        br
        = f.text_field :name
        - if @store.errors[:name].any?
          span.form-error = @store.errors.full_messages_for(:name)[0]
      .form_group
        = f.hidden_field :event_app_id, value: @event_app_id
        = f.label :store_desc
        br
        = f.text_area :store_desc, class: 'desc'
      = f.submit '登録'

app/views/stores/show.html.slim
.content
 .content-item
  h2.page-title = @store.name
  table.event-show
    tr
      th 出店者
      td = link_to @store.event_app.user.name, controller: 'users', action: 'show', id: @store.event_app.user
    tr
      th 出店概要
      td = text_url_to_link(simple_format(@store.store_desc))