config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'chat/show'

  root 'events#index'  
 
  resources :users
  resources :areas
  resources :prefs
  resources :events
  resources :event_apps do
    resources :stores
  end

  delete '/logout',to:'sessions#destroy'

  get '/event_msgs',to:'event_msgs#index'
  post '/event_msgs',to:'event_msgs#create'


  get '/event_msg_reps/new',to:'event_msg_reps#new'
  post '/event_msg_reps',to:'event_msg_reps#create'

  get '/msgs/index',to:'msgs#index'
  get '/msgs/select_user',to:'msgs#select_user'
  post '/msgs/select_user',to:'msgs#query_user'

  get '/msgs/:id',to:'msgs#new'
  post 'msgs/:id',to:'msgs#create'

  get '/home',to:'home#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
 
  get '*not_found',to:'application#routing_error'
  post '*not_found',to:'application#routing_error'

  mount ActionCable.server => '/cable'
end

app/models/event.rb
class Event < ApplicationRecord
  # モデルの関連定義
  belongs_to :user, foreign_key: 'user_id'
  belongs_to :pref, foreign_key: 'pref_id'
  has_many :event_apps, dependent: :destroy

  # 追加のattribute
  attribute :remove_img1, :boolean
  attribute :remove_img2, :boolean
  attribute :remove_img3, :boolean
  attribute :remove_img4, :boolean

  before_save do
    remove_photo_url1! if remove_img1
    remove_photo_url2! if remove_img2
    remove_photo_url3! if remove_img3
    remove_photo_url4! if remove_img4
  end

  # バリデーション
  validates :event_name, presence: true, length: { maximum: 255 }
  validates :event_date, presence: true
  validates :pref_id, presence: true
  validates :user_id, presence: true
  validates :event_published_flg, inclusion: { in: [false, true] }
  validates :event_detail, length: { maximum: 2000 }
  validates :city, length: { maximum: 255 }
  validates :place_detail, length: { maximum: 255 }
  validates :event_recruiting_flg, inclusion: { in: [false, true] }
  validates :event_recruit_number, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, allow_nil: true
  validates :event_entrance_fee, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, allow_nil: true
  validate :valid_date

  # カスタムのバリデーションメソッド
  def valid_date
    if event_recruit_start_date.present?
      if event_recruit_end_date.present?
        errors.add(:event_recruit_start_date, 'は募集終了日より前の日付で指定してください') if event_recruit_start_date > event_recruit_end_date
      end
    end
  end

  # ファイルアップロード
  mount_uploader :photo_url1, AvatarUploader
  mount_uploader :photo_url2, AvatarUploader
  mount_uploader :photo_url3, AvatarUploader
  mount_uploader :photo_url4, AvatarUploader

  # 区分値
  enum event_recruiting_flgs: { '募集しない' => false, '募集する' => true }
  enum event_published_flgs: { '下書き' => false, '公開' => true }

  # クエリ
  scope :search_with_pref, ->(pref_id) { where(pref_id: pref_id) }
  scope :search_with_start, ->(event_date_from) { where('event_date >= ?', event_date_from) }
  scope :search_with_end, ->(event_date_to) { where('event_date <= ?', event_date_to) }
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create destroy]
  PER = 9
  def index
    if params[:commit]
      @event_date_from = Time.zone.local(params['event_date_from(1i)'].to_i, params['event_date_from(2i)'].to_i, params['event_date_from(3i)'].to_i)
      @event_date_to = Time.zone.local(params['event_date_to(1i)'].to_i, params['event_date_to(2i)'].to_i, params['event_date_to(3i)'].to_i) if params['event_date_to(1i)'].present?
    else
      @event_date_from = Date.current.in_time_zone
      @event_date_to = nil
    end

    # events検索
    @events = Event.where(event_published_flg: true)
    # @pref = Pref.find(params:[:pref_id])
    @events = @events.search_with_start(@event_date_from) if @event_date_from
    @events = @events.search_with_end(@event_date_to) if @event_date_to
    if params[:pref_id].present?
      @pref = Pref.find(params[:pref_id])
      @events = @events.search_with_pref(params[:pref_id])
    end
    @events = @events.order(event_date: :asc).page(params[:page]).per(PER)
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(formatted_event_params)
    if @event.valid?
      begin
        ActiveRecord::Base.transaction do
          @event.save!
          # イベント参加者に作成者を追加
          event_app = EventApp.new
          event_app.event_id = @event.id
          event_app.user_id = current_user.id
          event_app.save!
        end
      rescue Exception => e
        p e
      end
      flash[:success] = 'イベントを登録しました'
      redirect_to events_path
    else
      flash.now[:error] = '不正な入力があります'
      render 'events/new'
    end
  end

  def edit
    @event = Event.find(params[:id])
    @event_app = EventApp.find_by(event_id: @event.id, user_id: current_user.id)
  end

  def update
    @event = Event.find(params[:id])
    @event_app = EventApp.find_by(event_id: @event.id, user_id: current_user.id)
    if @event.update(formatted_event_params)
      flash.now[:success] = '保存しました'
    else
      flash.now[:error] = '不正な入力があります'
    end
    render 'events/edit'
  end

  def show
    @event = Event.find(params[:id])
  end

  def destroy
    @event = current_user.events.find(params[:id])
    @event.destroy
    flash[:success] = 'イベントを削除しました'
    redirect_to event_apps_path
  end

  private

  def event_params
    params.require(:event).permit(
      :event_name,
      :event_date,
      :pref_id,
      :city,
      :event_published_flg,
      :event_recruiting_flg,
      :place_detail,
      :event_date,
      :event_recruit_start_date,
      :event_recruit_end_date,
      :event_recruit_number,
      :event_entrance_fee,
      :event_detail,
      :photo_url1,
      :photo_url2,
      :photo_url3,
      :photo_url4,
      :remove_img1,
      :remove_img2,
      :remove_img3,
      :remove_img4
    )
  end

  def formatted_event_params
    attrs = event_params.to_h
    attrs[:user_id] = current_user.id
    attrs[:event_date] = Time.zone.local(params[:event]['event_date(1i)'].to_i, params[:event]['event_date(2i)'].to_i, params[:event]['event_date(3i)'].to_i)
    attrs[:event_recruit_start_date] = Time.zone.local(params[:event]['event_recruit_start_date(1i)'].to_i, params[:event]['event_recruit_start_date(2i)'].to_i, params[:event]['event_recruit_start_date(3i)'].to_i)
    attrs[:event_recruit_end_date] = Time.zone.local(params[:event]['event_recruit_end_date(1i)'].to_i, params[:event]['event_recruit_end_date(2i)'].to_i, params[:event]['event_recruit_end_date(3i)'].to_i)
    attrs
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.slim
= form_with model: @event, local: true do |f|
    .form-group
      span.label = f.label :event_name
      = f.text_field :event_name
      - if @event.errors[:event_name].any?
        span.form-error = @event.errors.full_messages_for(:event_name)[0]
    .form-group.date-select
      span.label = f.label '開催日'
      = f.date_select :event_date, use_month_numbers: true, date_separator: '/'
      - if @event.errors[:event_date].any?
        span.form-error = @event.errors.full_messages_for(:event_date)[0]
    .form-group
      span.label = f.label '都道府県'
      = f.collection_select :pref_id, Pref.all, :id, :pref_name, prompt: '選択してください'
      - if @event.errors[:pref_id].any?
        span.form-error = @event.errors.full_messages_for(:pref_id)[0]
    .form-group
      span.label = f.label '市区町村'
      = f.text_field :city
      - if @event.errors[:city].any?
        span.form-error = @event.errors.full_messages_for(:city)[0]
    .form-group
      span.label = f.label '場所詳細'
      = f.text_field :place_detail
      - if @event.errors[:place_detail].any?
        span.form-error = @event.errors.full_messages_for(:place_detail)[0]
    .form-group
      span.label = f.label '出店者の募集'
      = f.select :event_recruiting_flg, options_for_select(Event.event_recruiting_flgs, @event.event_recruiting_flg)
    .form-group.date-select
      span.label = f.label '募集受付開始日'
      = f.date_select :event_recruit_start_date, use_month_numbers: true, date_separator: '/'
      - if @event.errors[:event_recruit_start_date].any?
        span.form-error = @event.errors.full_messages_for(:event_recruit_start_date)[0]
    .form-group.date-select
      span.label = f.label '募集受付締切日'
      = f.date_select :event_recruit_end_date, use_month_numbers: true, date_separator: '/', default: Date.current.in_time_zone
      - if @event.errors[:event_recruit_end_date].any?
        span.form-error = @event.errors.full_messages_for(:event_recruit_end_date)[0]
    .form-group
      span.label = f.label '募集人数'
      = f.text_field :event_recruit_number
      - if @event.errors[:event_recruit_number].any?
        span.form-error = @event.errors.full_messages_for(:event_recruit_number)[0]
    .form-group
      span.label = f.label '参加費'
      = f.text_field :event_entrance_fee
      - if @event.errors[:event_entrance_fee].any?
        span.form-error = @event.errors.full_messages_for(:event_entrance_fee)[0]
    .form-group
      span.label = f.label 'イベント詳細'
      = f.text_area :event_detail, class: 'desc'
      - if @event.errors[:event_detail].any?
        span.form-error = @event.errors.full_messages_for(:event_detail)[0]
    .form-group
      span.label = f.label '画像1'
      - if @event.photo_url1?
        =image_tag @event.photo_url1.url, class: 'prev-img show'
      - else
        =image_tag '', class: 'prev-img'
      = f.file_field :photo_url1, class: 'input-file'
      = f.hidden_field :remove_img1, value: false, class: 'remove-img'
      = f.button '画像クリア', type: :button, class: 'img-clear'
      - if @event.errors[:photo_url1].any?
        span.form-error = @event.errors.full_messages_for(:photo_url1)[0]

    .form-group
      span.label = f.label '画像2'
      - if @event.photo_url2?
        =image_tag @event.photo_url2.url, class: 'prev-img show'
      - else
        =image_tag '', class: 'prev-img'
      = f.file_field :photo_url2, class: 'input-file'
      = f.hidden_field :remove_img2, value: false, class: 'remove-img'
      = f.button '画像クリア', type: :button, class: 'img-clear'
      - if @event.errors[:photo_url2].any?
        span.form-error = @event.errors.full_messages_for(:photo_url2)[0]

    .form-group
      span.label = f.label '画像3'
      - if @event.photo_url3?
        =image_tag @event.photo_url3.url, class: 'prev-img show'
      - else
        =image_tag '', class: 'prev-img'
      = f.file_field :photo_url3, class: 'input-file'
      = f.hidden_field :remove_img3, value: false, class: 'remove-img'
      = f.button '画像クリア', type: :button, class: 'img-clear'
      - if @event.errors[:photo_url3].any?
        span.form-error = @event.errors.full_messages_for(:photo_url3)[0]

    .form-group
      span.label = f.label '画像4'
      - if @event.photo_url4?
        = image_tag @event.photo_url4.url, class: 'prev-img show'
      - else
        = image_tag '', class: 'prev-img'
      = f.file_field :photo_url4, class: 'input-file'
      = f.hidden_field :remove_img4, value: false, class: 'remove-img'
      = f.button '画像クリア', type: :button, class: 'img-clear'
      - if @event.errors[:photo_url4].any?
        span.form-error = @event.errors.full_messages_for(:photo_url4)[0]

    .form-group
      span.label = f.label '公開する'
      = f.select :event_published_flg, options_for_select(Event.event_published_flgs, @event.event_published_flg)
    = f.submit '登録する'

app/views/events/edit.html.slim
.content
  p.back-to
    | <a href="#{event_app_path(@event_app.id)}"><i class="fas fa-arrow-left"></i></a>
  .content-item
    h2.page-title イベント編集
    = render 'events/form'
    p.event-new = link_to '削除する', event_path(@event), class: 'btn-min', method: :delete, data: { confirm: '本当に削除してよろしいでしょうか？' }

app/views/events/index.html.slim
section.search-config
  h3.search-config-title エリア・日付で絞り込む
  = form_with local: true, method: :get do |f|
      table
        tr
          th = f.label :都道府県

          - if @pref
            td.select-pref = f.collection_select :pref_id, Pref.all, :id, :pref_name, prompt: '選択してください', selected: @pref.id
          - else
            td.select-pref = f.collection_select :pref_id, Pref.all, :id, :pref_name, prompt: '選択してください'
        tr
          th = f.label :開催日
          td.select-date
            |
              #{f.date_select :event_date_from, selected: @event_date_from, use_month_numbers: true, date_separator: '/'}
                <br>
                <span> 〜 </span>
                <br>
              #{f.date_select :event_date_to, selected: @event_date_to, use_month_numbers: true, include_blank: true, date_separator: '/'}
      = f.submit '検索する'

section.event-result
  - if @pref
    h2.page-title = "#{@pref.pref_name}のハンドメイドイベント"
  - else
    h2.page-title = '全国のハンドメイドイベント'
  -if @events.present?
    -@events.each do |event|
      = link_to event_path(event) do
        dl.event
          dt
            p = event.event_name
          dd
            .list-img
              - if event.photo_url1?
                p.title-img = image_tag event.photo_url1.url, class: 'img-thum'
              - else
                p.title-img = image_tag 'no-image.png', class: 'img-thum'
            .list-desc
              p = "開催日時: #{I18n.l event.event_date, format: :full_date}"
              p = "開催場所: #{event.pref.pref_name}"
              p = "主催者：　#{event.user.nick_name}"
            .detail-icon
              = icon 'fas', 'chevron-right'

  -else
    p 検索結果がありませんでした。
  = paginate @events

app/views/events/new.html.slim
.content
  .content-item
    h2.page-title イベント登録
    = render 'events/form'

app/views/events/show.html.slim
.content
  .content-item
    h2.page-title = @event.event_name
    - if @event.photo_url1?
        p.title-img = image_tag @event.photo_url1.url, class: 'title-img-thum-l'
    - else
        p.title-img = image_tag 'no-image.png', class: 'img-thum-l'
    br
    table.event-show
      tr
        th 開催日時
        td = I18n.l @event.event_date, format: :full_date
      tr
        th 主催者
        td = link_to @event.user.nick_name, controller: 'users', action: 'show', id: @event.user
      tr
        th 開催場所
        td#address = "#{@event.pref.pref_name} #{@event.city} #{@event.place_detail}"
      tr
        th 出店募集期間
        td = "#{@event.event_recruit_start_date.strftime('%Y年%m月%d日')} 〜 #{@event.event_recruit_end_date.strftime('%Y年%m月%d日')}"
      tr
        th 開催概要
        td = @event.event_detail
      tr
        th 募集人数
        td = @event.event_recruit_number
      tr
        th 参加費
        td = @event.event_entrance_fee
      tr
        th 出店者
        td
          - @event.event_apps.each do |event_app|
              -if event_app.stores.present?
                span.event-app = link_to event_app.user.nick_name, event_app_store_path(event_app, event_app.stores[0])
              -else
                span.event-app = event_app.user.nick_name

    #map

    br
    - if current_user.nil? || (current_user.id != @event.user.id and !is_apply_event?)
      = form_with model: @event, url: '/event_apps', method: :post, local: true, class: 'event-detail' do |f|
        = f.hidden_field :event_id, value: @event.id
        = f.submit '応募する', class: 'submit'

javascript:
  var geocoder;
  var map;
  function initMap() {
    geocoder = new google.maps.Geocoder();
    var latlng = new google.maps.LatLng(-34.397, 150.644);
    var mapOptions = {
      zoom: 15,
      center: latlng
    }
    map = new google.maps.Map(document.getElementById('map'), mapOptions);
    codeAddress();
  }

  function codeAddress() {
    var address = document.getElementById('address').innerText;
    console.log(address)
    geocoder.geocode( { 'address': address}, function(results, status) {
      if (status == 'OK') {
        map.setCenter(results[0].geometry.location);
        var marker = new google.maps.Marker({
            map: map,
            position: results[0].geometry.location
        });
      } else {
        alert('Geocode was not successful for the following reason: ' + status);
      }
    });
  }

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBHNdZARvABHOXfS0uBb6n5aCFxS-JAoho&callback=initMap" async defer></script>