config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'chat/show'

  root 'events#index'  
 
  resources :users
  resources :areas
  resources :prefs
  resources :events
  resources :event_apps do
    resources :stores
  end

  delete '/logout',to:'sessions#destroy'

  get '/event_msgs',to:'event_msgs#index'
  post '/event_msgs',to:'event_msgs#create'


  get '/event_msg_reps/new',to:'event_msg_reps#new'
  post '/event_msg_reps',to:'event_msg_reps#create'

  get '/msgs/index',to:'msgs#index'
  get '/msgs/select_user',to:'msgs#select_user'
  post '/msgs/select_user',to:'msgs#query_user'

  get '/msgs/:id',to:'msgs#new'
  post 'msgs/:id',to:'msgs#create'

  get '/home',to:'home#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
 
  get '*not_found',to:'application#routing_error'
  post '*not_found',to:'application#routing_error'

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
  # モデルの関連
  has_many :prefs

  # バリデーション
  validates :area_name, presence: true, length: { maximum: 50 }, uniqueness: { case_sensitive: false }
end

app/models/event.rb
class Event < ApplicationRecord
  # モデルの関連定義
  belongs_to :user, foreign_key: 'user_id'
  belongs_to :pref, foreign_key: 'pref_id'
  has_many :event_apps, dependent: :destroy

  # 追加のattribute
  attribute :remove_img1, :boolean
  attribute :remove_img2, :boolean
  attribute :remove_img3, :boolean
  attribute :remove_img4, :boolean

  before_save do
    remove_photo_url1! if remove_img1
    remove_photo_url2! if remove_img2
    remove_photo_url3! if remove_img3
    remove_photo_url4! if remove_img4
  end

  # バリデーション
  validates :event_name, presence: true, length: { maximum: 255 }
  validates :event_date, presence: true
  validates :pref_id, presence: true
  validates :user_id, presence: true
  validates :event_published_flg, inclusion: { in: [false, true] }
  validates :event_detail, length: { maximum: 2000 }
  validates :city, length: { maximum: 255 }
  validates :place_detail, length: { maximum: 255 }
  validates :event_recruiting_flg, inclusion: { in: [false, true] }
  validates :event_recruit_number, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, allow_nil: true
  validates :event_entrance_fee, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, allow_nil: true
  validate :valid_date

  # カスタムのバリデーションメソッド
  def valid_date
    if event_recruit_start_date.present?
      if event_recruit_end_date.present?
        errors.add(:event_recruit_start_date, 'は募集終了日より前の日付で指定してください') if event_recruit_start_date > event_recruit_end_date
      end
    end
  end

  # ファイルアップロード
  mount_uploader :photo_url1, AvatarUploader
  mount_uploader :photo_url2, AvatarUploader
  mount_uploader :photo_url3, AvatarUploader
  mount_uploader :photo_url4, AvatarUploader

  # 区分値
  enum event_recruiting_flgs: { '募集しない' => false, '募集する' => true }
  enum event_published_flgs: { '下書き' => false, '公開' => true }

  # クエリ
  scope :search_with_pref, ->(pref_id) { where(pref_id: pref_id) }
  scope :search_with_start, ->(event_date_from) { where('event_date >= ?', event_date_from) }
  scope :search_with_end, ->(event_date_to) { where('event_date <= ?', event_date_to) }
end

app/models/event_app.rb
class EventApp < ApplicationRecord
  belongs_to :event
  belongs_to :user
  has_many :stores

  validates_uniqueness_of :user_id, scope: :event_id
end

app/models/event_msg.rb
class EventMsg < ApplicationRecord
  # モデルの関連
  belongs_to :event
  belongs_to :user, foreign_key: 'sender_id'
  has_many :event_msg_reps, dependent: :destroy

  # バリデーション
  validates :msg, length: { maximum: 400 }

  mount_uploader :photo_url, AvatarUploader
end

app/models/event_msg_rep.rb
class EventMsgRep < ApplicationRecord
  belongs_to :event_msg
  belongs_to :user, foreign_key: 'rep_user_id'

  # バリデーション
  validates :msg, length: { maximum: 400 }

  mount_uploader :photo_url, AvatarUploader
end

app/models/msg.rb
class Msg < ApplicationRecord
  # モデルの関連
  belongs_to :sender, class_name: 'User'
  belongs_to :reciever, class_name: 'User'

  # バリデーション
  validates :msg, length: { maximum: 400 }

  mount_uploader :photo_url, AvatarUploader
end

app/models/msg_user.rb
class MsgUser < ApplicationRecord
  belongs_to :user
  belongs_to :relation, class_name: 'User'
  attr_accessor :room_id
  def room_id
    if user_id < relation_id
      user_id.to_s + '-' + relation_id.to_s
    else
      relation_id.to_s + '-' + user_id.to_s
    end
  end
end

app/models/pref.rb
class Pref < ApplicationRecord
  # モデルの関連
  belongs_to :area, foreign_key: 'area_id'

  # バリデーション
  validates :pref_id, presence: true, length: { maximum: 3 }, uniqueness: { case_sensitive: false }
  validates :pref_name, presence: true, length: { maximum: 50 }
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :event_app, foreign_key: 'event_app_id'
  belongs_to :user, foreign_key: 'store_owner_id'

  validates :name, presence: true
  validates :store_desc, length: { maximum: 2000 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :events, dependent: :destroy
  mount_uploader :avatar_path, AvatarUploader

  attribute :remove_img, :boolean

  before_save do
    remove_avatar_path! if remove_img
    self.nick_name ||= name
  end

  # バリデーション
  # email
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :name, presence: true

  # パスワード
  # has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # 渡されたトークンがダイジェスト一致したらtrueを返す
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return if digest.nil?

    BCrypt::Password.new(digest).is_password?(token)
  end
end

app/controllers/event_apps_controller.rb
class EventAppsController < ApplicationController
  before_action :authenticate_user!, only: %i[index create destroy]
  def index
    @event_apps = EventApp.where(user_id: current_user.id).includes(:event).order('events.event_date desc')
  end

  def create
    event_app = EventApp.new
    event_app.event_id = params[:event][:event_id]
    event_app.user_id = current_user.id
    event_app.save!
    flash[:success] = 'イベントに応募しました'
    redirect_to event_app_path(event_app)
  end

  def show
    @event_app = EventApp.find(params[:id])
    redirect_to event_apps_path if @event_app.user_id != current_user.id
  end

  def destroy
    event_app = EventApp.find(params[:id])
    event_app.destroy
    flash[:success] = '応募を取消ました'
    redirect_to event_apps_path
  end
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/event_apps_helper.rb
module EventAppsHelper
end

app/helpers/event_msgs_helper.rb
module EventMsgsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/msgs_helper.rb
module MsgsHelper
end

app/helpers/profs_helper.rb
module ProfsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def is_apply_event?
    cid = current_user
    if cid.nil?
      false
    else
      !!EventApp.find_by(user_id: cid, event_id: params[:id])
    end
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/signin_helper.rb
module SigninHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/event_apps/index.html.slim
.content
  p.event-new = link_to 'イベントを新規作成', new_event_path, class: 'btn'
  br
  section.event-app-list
    h2.page-title 参加イベント一覧
    -if @event_apps.empty?
      p 参加予定のイベントはありません。
    -@event_apps.each do |event_app|
      =link_to event_app_path(event_app) do
        dl.event
          dt 
            - if event_app.event.user.id == current_user.id
              p 
                | #{event_app.event.event_name} <span class='owner'>主催</span>
            - else
              p = event_app.event.event_name
          dd
            - if event_app.event.photo_url1?
              p.title-img = image_tag event_app.event.photo_url1.url, class: 'img-thum'
            - else
              p.title-img = image_tag 'no-image.png', class: 'img-thum'
            p = "開催日時: #{event_app.event.event_date.strftime('%Y年%m月%d日')}"
            p = "主催者：　#{event_app.event.user.name}"
  br

app/views/event_apps/show.html.slim
.content
  p.back-to
    | <a href="#{event_apps_path}"><i class="fas fa-arrow-left"></i></a>
  .content-item
    h2.page-title = @event_app.event.event_name
    - if @event_app.event.photo_url1?
        p.title-img = image_tag @event_app.event.photo_url1.url, class: 'img-thum'
    - else
        p.title-img = image_tag 'no-image.png', class: 'img-thum'
    p = "開催日時: #{@event_app.event.event_date.strftime('%Y年%m月%d日')}"
    p = "主催者：　#{@event_app.event.user.name}"
    ul.event-app-btn-list
      li = link_to event_msgs_path(event_id: @event_app.event_id), class: 'btn-min' do
          = icon 'fas', 'comment'
          = ' チャット'
      li = link_to event_app_stores_path(@event_app), class: 'btn-min' do
          = icon 'fas', 'store'
          = ' 出店情報'
      - if @event_app.event.user.id == current_user.id
        li = link_to edit_event_path(@event_app.event), class: 'btn-min' do
          = icon 'fas', 'edit'
          = ' イベント編集'
      - else
        li = link_to '応募をやめる', event_app_path(@event_app), class: 'btn-min', method: :delete, data: { confirm: '応募を取り消します' }